### ISSUE TITLE
Design feedback

### ISSUE THREAD

**Issue by jsocooper** [gitburn/gitburn#644]
I downloaded the new Desktop app to kick the tires and offer some feedback. Overall I like most of the UI changes, including the way the repo list is handled now and the top navigation which feels more structured.

### General
* First time I fetched, this was present for a very long time (+30min...still going actually).
* The square buttons feel out of place given rounded input boxes, and generally the rounded button styles on .com and OS X; square buttons might feel right in Windows, but they def feel out of place here on OS X

### Welcome screen

  
* Is there any way to migrate my repo setup from the old Desktop app? It'd be a shame if I had to manually setup or clone down all of the repos I had all over again.
* These buttons with square edges feel out of place on OSX, since it neither matches .com or OS X button corner conventions
* Is there any way to migrate my repo setup from the old Desktop app? It'd be a shame if I had to manually setup or clone down all of the repos I had all over again.

### Blankslate

* I literally have no idea what to do next; some instructions for setting up your first repo (or importing existing repos) would be helpful

**Comment by HashimotoYT** [comment]
Thanks for the feedback @jsocooper. You're right in that what you see now is a very early version of what we're striving towards and as far as implementing our design vision goes we have a lot of work still left do to.

The welcome flow is currently a first-pass, @olegtiger is working on polishing in #624. This holds true for most parts of the app right now. We've opted for an approach of doing the broad strokes first and then polishing as we go.

Our latest mocks which represent our goal (although we'll revise as we develop) are in #549

Given your error when you tried to push this is very likely a bug in our handling of failures in fetch. Thanks for pointing it out.

Yup, this is definitely something we'll get to before shipping. We've talked about adopting a layout here that matches that of the initial welcome screen with a big friendly illustration to get you started. This is one of the areas that we didn't have time to create mocks for in our latest design session but rest assured, it's being thought of.

This is being discussed in #186. My gut tells me that yes, we should perform some sort of migration for existing users.

Yeah, while the square buttons was intentional in our mocks I think we could play with a (very subtle) radius for buttons, especially seeing how we already round input fields. I think what we were trying to avoid was an overly round appearance, the app design is very much built on hard rectangles.
